version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-docker:/usr/local/bin
      - ./kube:/root/.kube          # stores kubeconfig
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    entrypoint:
      - /bin/bash
      - -c
      - |
        # Install Docker CLI + kubectl + Helm before Jenkins starts
        apt update &&
        apt install -y docker.io curl apt-transport-https gnupg &&
        
        # Install kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&
        chmod +x kubectl &&
        mv kubectl /usr/local/bin/ &&

        # Install Helm
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash &&

        # Start Jenkins
        exec /usr/local/bin/jenkins.sh
volumes:
  jenkins_home:
